- name: Get VmWare url
  pause:
    prompt: "Inserire l'URL per scaricare VmWareHorizon"
  register: vmware_url
  until: vmware_url.user_input is match("https://.*.vmware.com/software/view/viewclients/.*/VMware-Horizon-Client.*.x64.bundle")

- name: Check client is already download
  stat:
    path: ~/{{ vmware_url.user_input | basename }}
  register: stat_client

- name: Get horizon client
  get_url:
    url: "{{ vmware_url.user_input }}"
    dest: ~/.
    mode: a+x
  when: not stat_client.stat.exists

- name: Create link needed
  become: true
  file:
    src: /usr/lib/x86_64-linux-gnu/{{ item.src }}
    dest: /usr/lib/x86_64-linux-gnu/{{ item.dst }}
    state: link
  loop:
    - { src: libgstreamer-1.0.so.0, dst: libgstreamer-0.10.so.0 }
    - { src: libgstapp-1.0.so.0, dst: libgstapp-0.10.so.0 }
    - { src: libgstbase-1.0.so.0, dst: libgstbase-0.10.so.0 }

- name: Create Wmware config directory
  copy:
    src: ../files/.vmware/
    dest: ~/.vmware

- name: Ask VDI url/IP
  pause:
    prompt: "Inserire l'URL oppure l'indirizzo IP del server VDI"
  register: vdi_url_ip
  until: ( vdi_url_ip.user_input | length > 0 )

- name: Set VDI url/ip
  lineinfile:
    path: ~/.vmware/view-preferences
    regex: view.defaultBroker = ''
    line: view.defaultBroker = '{{ vdi_url_ip.user_input }}'

- name: Test Vmware is already installed
  shell: command -v vmware-view > /dev/null 2>&1
  register: vmware_installed

- name: Run VmWare installation
  become: true
  shell: "{{ ansible_facts['env']['HOME'] }}/{{ vmware_url.user_input | basename }}"
  args:
    executable: /bin/bash
