- name: Check client is already download
  stat:
    path: ~/VMware-Horizon-Client-5.5.0-16946361.x64.bundle
  register: stat_client

- name: Get horizon client
  get_url:
    url: https://download3.vmware.com/software/view/viewclients/CART21FQ3/VMware-Horizon-Client-5.5.0-16946361.x64.bundle
    dest: ~/.
    mode: a+x
  when: not stat_client.stat.exists

- name: Create link needed
  become: true
  file:
    src: /usr/lib/x86_64-linux-gnu/{{ item.src }}
    dest: /usr/lib/x86_64-linux-gnu/{{ item.dst }}
    state: link
  loop:
    - { src: libgstreamer-1.0.so.0, dst: libgstreamer-0.10.so.0 }
    - { src: libgstapp-1.0.so.0, dst: libgstapp-0.10.so.0 }
    - { src: libgstbase-1.0.so.0, dst: libgstbase-0.10.so.0 }

- name: Create Wmware config directory
  copy:
    src: ../files/.vmware/
    dest: ~/.vmware

- name: Ask VDI url/IP
  pause:
    prompt: "Inserire l'URL oppure l'indirizzo IP del server VDI"
  register: vdi_url_ip

- name: Set VDI irl/ip
  lineinfile:
    path: ~/.vmware/view-preferences
    regex: view.defaultBroker = ''
    line: view.defaultBroker = '{{ vdi_url_ip }}'