- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  apt:
    update_cache: yes

- name: Update all software
  become: true
  apt:
    name: "*"
    state: latest

- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: Install necessary software
  become: true
  apt:
    pkg:
      - git
      - ansible
      - openssh-server
      - vino
      - sane
      - vim

- name: Disable Cups service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - cups
    - cups-browsed
