- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  apt:
    update_cache: yes

- name: Update all software
  become: true
  apt:
    name: "*"
    state: latest

- name: Remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: Install necessary software
  become: true
  apt:
    pkg:
      - git
      - ansible
      - openssh-server
      - vino
      - sane
      - vim
      - libvdpau-va-gl1

- name: Disable Cups service
  become: true
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - cups
    - cups-browsed

- name: Dconf gnome-session-properties
  community.general.dconf:
    key: "{{ item }}"
    state: absent
  loop:
    - /org/gnome/desktop/notifications/application/gnome-session-properties
    - /org/gnome/desktop/notifications/application/org-gnome-calculator
    - /org/gnome/desktop/notifications/application/org-gnome-tweaks
    - /org/gnome/desktop/notifications/application/software-properties-gtk
    - /org/gnome/desktop/notifications/application/software-properties-livepatch
    - /org/gnome/desktop/screensaver

- name: Dconf gnome-session-properties org/gnome/desktop/notifications/application/gnome-session-properties
  community.general.dconf:
    key: "/org/gnome/desktop/notifications/application/gnome-session-properties"
    value: "true"

- name: Dconf vino /org/gnome/desktop/remote-access/require-encryption
  dconf:
    key: '/org/gnome/desktop/remote-access/require-encryption'
    value: "false"

- name: Dconf locksreen /org/gnome/settings-daemon/plugins/power/idle-delay
  dconf:
    key: '/org/gnome/settings-daemon/plugins/power/idle-delay'
    value: "uint32 0"


- name: Dconf disable notification /org/gnome/desktop/notifications/show-banners
  dconf:
    key: '/org/gnome/desktop/notifications/show-banners'
    value: "false"